use Reviews

CREATE TABLE Info (
ID INT PRIMARY KEY IDENTITY(1,1),
Comment VARCHAR(255),
Rate INT NOT NULL CHECK(Rate > 0 AND Rate <= 5),
PlaceID INT NOT NULL,
FOREIGN KEY (PlaceID) REFERENCES Places (PlaceID),
UserID INT NOT NULL,
FOREIGN KEY (UserID) REFERENCES Users (UserID),
DTime DATETIME DEFAULT GETDATE()
)
