--Показать поля ProductModelID, ProductDescriptionID, CultureID из таблицы Production.ProductModelProductDescription.
SELECT ProductModelID, ProductDescriptionID, CultureID
FROM Production.ProductModelProductDescriptionCulture